#!/bin/bash
if [ $# = 0 ]; then
	echo "Usage: {$0} executable_name"
	exit 1
fi
cp ~/scripts/templates/c.vimspector.json ./.vimspector.json
sed "s|PROJECT_PATH|$(pwd)|g" ./.vimspector.json -i
sed "s|build/PROJECT_NAME|$1|g" .vimspector.json -i

