#!/bin/python3
import os, sys
import subprocess

TEMPLATES_DIR = f"{os.path.expanduser('~')}/scripts/templates"
pwd = os.getcwd()

if len(sys.argv) >= 2:
    pr_name = sys.argv[1]
else:
    pr_name = input("Insert project name:")
    while pr_name.strip() == "":
        pr_name = input("(Name must not be empty) Insert project name: ")

if not os.path.exists(f"{pwd}/{pr_name}"):
    mainfile_template = open(f"{TEMPLATES_DIR}/main.py","r").read()
    mainfile_template = mainfile_template.replace("PROJECT_NAME",pr_name)
    mainfile = open(f"{pwd}/{pr_name}.py","w")
    mainfile.write(mainfile_template)
    mainfile.close()


debugconf_template = open(f"{TEMPLATES_DIR}/py.vimspector.json","r").read()
debugconf_template = debugconf_template.replace("PROJECT_NAME",pr_name).replace("PROJECT_PATH",pwd)

debugconf = open(f"{pwd}/.vimspector.json","w")
debugconf.write(debugconf_template)
debugconf.close()



ret_val = subprocess.run(["git","status"],stderr=subprocess.DEVNULL,stdout=subprocess.DEVNULL)
if ret_val.returncode != 0:
    gitignore = open(f"{pwd}/.gitignore","w")
    gitignore.write("")
    gitignore.close()
    subprocess.run(["git", "init"])
